server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
           - Path=/api/inventory/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
