spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      paymentServiceCB:
        timeoutDuration: 5s